Repository Step3-kakao-tech-campus/Team12_BE, pull requests merged in 2023-10, with the labels that each got.

#9 feat: 공고 현황 페이지 무한스크롤
  .gitignore
  pickupShuttle/build.gradle
  pickupShuttle/src/main/generated/pickup_shuttle/pickup/domain/QUser.java
  pickupShuttle/src/main/generated/pickup_shuttle/pickup/domain/account/QAccount.java
  pickupShuttle/src/main/generated/pickup_shuttle/pickup/domain/beverage/QBeverage.java
  pickupShuttle/src/main/generated/pickup_shuttle/pickup/domain/board/QBoard.java
  pickupShuttle/src/main/generated/pickup_shuttle/pickup/domain/match/QMatch.java
  pickupShuttle/src/main/generated/pickup_shuttle/pickup/domain/store/QStore.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/_core/errors/GlobalExceptionHandler.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/_core/errors/exception/Exception400.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/_core/errors/exception/Exception500.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/_core/utils/ApiUtils.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/config/BooleanConverter.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/_core/utils/ApiUtils.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/account/Account.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/beverage/Beverage.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/board/Board.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/board/BoardController.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/board/BoardRepositoryCustom.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/board/BoardRepositoryImpl.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/board/BoardService.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/board/dto/response/BoardListResponseDTO.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/match/Match.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/store/Store.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/user/UserController.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/user/UserRepository.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/user/UserRequest.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/user/UserService.java
  pickupShuttle/src/main/resources/application-local.yml
  pickupShuttle/src/main/resources/application.properties
  pickupShuttle/src/main/resources/application.yml
  pickupShuttle/src/main/resources/db/teardown.sql
  pickupShuttle/src/test/java/pickup_shuttle/pickup/domain/board/BoardControllerTest.java
  pickupShuttle/src/test/java/pickup_shuttle/pickup/domain/user/UserControllerTest.java
Labels: ✨feature

#15 카카오 Oauth2 로그인 연동
  pickupShuttle/build.gradle
  pickupShuttle/src/main/java/pickup_shuttle/pickup/PickupApplication.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/oauth2/CustomOauth2User.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/oauth2/OAuthAttributes.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/oauth2/handler/OAuth2LoginFailureHandler.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/oauth2/handler/OAuth2LoginSuccessHandler.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/oauth2/service/CustomOAuth2UserService.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/oauth2/userinfo/KakaoOAuth2UserInfo.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/oauth2/userinfo/OAuth2UserInfo.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/refreshToken/RefreshToken.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/refreshToken/RefreshTokenRepository.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/refreshToken/TokenDTO.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/user/User.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/user/UserController.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/user/UserRepository.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/user/UserRole.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/user/UserService.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/user/dto/SignUpRqDTO.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/security/SecurityConfig.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/security/filter/JwtAuthenticationProcessingFilter.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/security/service/JwtService.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/security/util/PasswordUtil.java
  pickupShuttle/src/main/resources/application-jwt.yml
  pickupShuttle/src/main/resources/application-oauth.yml
  pickupShuttle/src/main/resources/application.properties
  pickupShuttle/src/main/resources/templates/index.html
  pickupShuttle/src/main/resources/templates/registerInput.html
  pickupShuttle/src/main/resources/templates/signup.html
Labels: ✨feature

#18 feat: 공고 상세페이지
  pickupShuttle/src/main/generated/pickup_shuttle/pickup/domain/account/QAccount.java
  pickupShuttle/src/main/generated/pickup_shuttle/pickup/domain/board/QBoard.java
  pickupShuttle/src/main/generated/pickup_shuttle/pickup/domain/match/QMatch.java
  pickupShuttle/src/main/generated/pickup_shuttle/pickup/domain/refreshToken/QRefreshToken.java
  pickupShuttle/src/main/generated/pickup_shuttle/pickup/domain/user/QUser.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/PickupApplication.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/config/BooleanConverter.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/account/Account.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/account/AccountRepository.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/board/Board.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/board/BoardController.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/board/BoardService.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/board/dto/response/BoardDetailAfterRpDTO.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/board/dto/response/BoardDetailBeforeRpDTO.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/board/dto/response/BoardListRpDTO.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/board/repository/BoardRepository.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/board/repository/BoardRepositoryCustom.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/board/repository/BoardRepositoryImpl.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/match/Match.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/match/MatchRepository.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/user/User.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/user/UserController.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/user/UserRepository.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/user/UserRequest.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/user/UserService.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/user/dto/SignUpRqDTO.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/user/dto/request/NicknameCheckRqDTO.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/user/dto/request/RegisterRqDTO.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/user/dto/request/SignUpRqDTO.java
  pickupShuttle/src/main/resources/application-local.yml
  pickupShuttle/src/main/resources/db/teardown.sql
  pickupShuttle/src/test/java/pickup_shuttle/pickup/domain/board/BoardControllerTest.java
  pickupShuttle/src/test/java/pickup_shuttle/pickup/domain/user/UserControllerTest.java
Labels: ✨feature

#34 fix: issue #14
  .idea/compiler.xml
  .idea/misc.xml
  pickupShuttle/src/main/java/pickup_shuttle/pickup/PickupApplication.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/config/LoginUserArgument.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/oauth2/CustomOauth2User.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/oauth2/handler/OAuth2LoginSuccessHandler.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/oauth2/service/CustomOAuth2UserService.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/oauth2/userinfo/KakaoOAuth2UserInfo.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/refreshToken/RefreshTokenRepository.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/refreshToken/dto/response/AccessTokenRpDTO.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/user/UserController.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/security/SecurityConfig.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/security/filter/JwtAuthenticationProcessingFilter.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/security/service/JwtService.java
  pickupShuttle/src/main/resources/application-local.yml
  pickupShuttle/src/main/resources/templates/errorPage.html
Labels: 🐛bug

#37 feat :(#36) 공고 페이지 삭제, feat : (#35) 인증 상태 확인
  .github/pull_request_template.md
  pickupShuttle/src/main/java/pickup_shuttle/pickup/config/LoginUserArgument.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/board/BoardController.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/board/BoardService.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/board/dto/request/BoardWriteRqDTO.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/board/repository/BoardRepository.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/user/UserController.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/user/UserService.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/user/dto/request/NicknameCheckRqDTO.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/user/dto/request/RegisterRqDTO.java
  pickupShuttle/src/main/resources/application-local.yml
  pickupShuttle/src/main/resources/db/teardown.sql
  pickupShuttle/src/test/java/pickup_shuttle/pickup/domain/board/BoardControllerTest.java
  pickupShuttle/src/test/java/pickup_shuttle/pickup/domain/user/UserControllerTest.java
Labels: ✨feature

#40 fix: issue #38, issue #39
  pickupShuttle/src/main/java/pickup_shuttle/pickup/config/LoginUserArgument.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/board/BoardController.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/board/BoardService.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/board/dto/response/BoardListRpDTO.java
  pickupShuttle/src/main/resources/db/teardown.sql
  pickupShuttle/src/test/java/pickup_shuttle/pickup/domain/board/BoardControllerTest.java
Labels: 🐛bug

#42 fix: issue #41
  pickupShuttle/src/main/java/pickup_shuttle/pickup/security/service/JwtService.java
Labels: 🐛bug

#47 fix: issue #46, #48
  pickupShuttle/src/main/java/pickup_shuttle/pickup/config/ErrorMessage.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/board/BoardService.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/user/UserService.java
  pickupShuttle/src/main/resources/application-jwt.yml
  pickupShuttle/src/main/resources/db/teardown.sql
  pickupShuttle/src/test/java/pickup_shuttle/pickup/domain/board/BoardControllerTest.java
Labels: 🐛bug

#52 fix, feat: issue #49, #50
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/board/BoardService.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/oauth2/OAuthAttributes.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/oauth2/handler/OAuth2LoginSuccessHandler.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/oauth2/service/CustomOAuth2UserService.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/refreshToken/dto/response/RefreshTokenRpDTO.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/user/UserController.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/user/UserRepository.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/user/UserService.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/user/dto/request/UserModifyRqDTO.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/user/dto/response/ModifyUserRpDTO.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/security/filter/JwtAuthenticationProcessingFilter.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/security/service/JwtService.java
  pickupShuttle/src/main/resources/templates/userModify.html
Labels: 🐛bug, ✨feature

#58 feat : 공고글 수정(#54), 이미지 업로드(#55), Presigned URL (#56) #57
  pickupShuttle/.gitignore
  pickupShuttle/build.gradle
  pickupShuttle/src/main/java/pickup_shuttle/pickup/config/NotSpace.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/config/NotSpaceValidator.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/config/S3Config.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/board/BoardController.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/board/BoardService.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/board/dto/request/BoardModifyRqDTO.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/board/dto/request/BoardWriteRqDTO.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/board/dto/response/BoardModifyRpDTO.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/board/repository/BoardRepository.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/user/UserController.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/user/UserService.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/user/dto/request/UserUploadImageRqDTO.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/user/dto/response/UserGetImageUrlRpDTO.java
  pickupShuttle/src/main/resources/application.yml
  pickupShuttle/src/main/resources/db/teardown.sql
  pickupShuttle/src/test/java/pickup_shuttle/pickup/domain/board/BoardControllerTest.java
Labels: ✨feature

#63 feat: mypage 조회, 로그 파일에 로그 기록하기
  .gitignore
  pickupShuttle/.gitignore
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/user/UserController.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/user/UserService.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/user/dto/response/UserMyPageRpDTO.java
  pickupShuttle/src/main/resources/logback-spring.xml
  pickupShuttle/src/test/java/pickup_shuttle/pickup/domain/user/UserControllerTest.java
Labels: ✨feature

#64 전남대_12조_픽업셔틀_6주차
  pickupShuttle/.gitignore
  pickupShuttle/build.gradle
  pickupShuttle/src/main/java/pickup_shuttle/pickup/config/ErrorMessage.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/config/NotSpace.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/config/NotSpaceValidator.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/config/S3Config.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/board/BoardController.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/board/BoardService.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/board/dto/request/BoardModifyRqDTO.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/board/dto/request/BoardWriteRqDTO.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/board/dto/response/BoardModifyRpDTO.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/board/repository/BoardRepository.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/oauth2/OAuthAttributes.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/oauth2/handler/OAuth2LoginSuccessHandler.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/oauth2/service/CustomOAuth2UserService.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/refreshToken/dto/response/RefreshTokenRpDTO.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/user/UserController.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/user/UserRepository.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/user/UserService.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/user/dto/request/UserModifyRqDTO.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/user/dto/request/UserUploadImageRqDTO.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/user/dto/response/ModifyUserRpDTO.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/domain/user/dto/response/UserGetImageUrlRpDTO.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/security/filter/JwtAuthenticationProcessingFilter.java
  pickupShuttle/src/main/java/pickup_shuttle/pickup/security/service/JwtService.java
  pickupShuttle/src/main/resources/application-jwt.yml
  pickupShuttle/src/main/resources/application.yml
  pickupShuttle/src/main/resources/db/teardown.sql
  pickupShuttle/src/main/resources/templates/userModify.html
  pickupShuttle/src/test/java/pickup_shuttle/pickup/domain/board/BoardControllerTest.java
Labels: 🙋‍♂️ Request Review
