Repository Step3-kakao-tech-campus/Team12_BE, pull requests merged in 2023-11, with the labels that each got.

#73 fix: 프록시 서버 접속이 안되는 현상 해결 (#72)
  Dockerfile
  src/main/java/pickup_shuttle/pickup/domain/board/BoardService.java
  src/main/java/pickup_shuttle/pickup/domain/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/pickup_shuttle/pickup/domain/oauth2/service/CustomOAuth2UserService.java
  src/main/java/pickup_shuttle/pickup/security/SecurityConfig.java
  src/main/java/pickup_shuttle/pickup/security/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/pickup_shuttle/pickup/security/service/JwtService.java
Labels: 🐛bug

#84 fix: application.yml 파일 수정 및 local 설정값 삭제
  .idea/compiler.xml
  .idea/misc.xml
  .idea/modules/pickupShuttle.main.iml
  .idea/modules/team12_deploy.iml
  .idea/modules/team12_deploy.test.iml
  src/main/resources/application-local-aws.yml
  src/main/resources/application-local-db.yml
  src/main/resources/application-local-oauth.yml
  src/main/resources/application.yml
Labels: 🐛bug

#89 fix: 회원가입 응답에 닉네임 추가
  src/main/java/pickup_shuttle/pickup/domain/user/UserService.java
  src/main/java/pickup_shuttle/pickup/domain/user/dto/response/CreateUserRp.java
Labels: hotfix

#90 refactor: 배포를 위한 코드 리팩토링
  src/main/java/pickup_shuttle/pickup/config/WebConfig.java
  src/main/java/pickup_shuttle/pickup/domain/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/pickup_shuttle/pickup/domain/user/UserController.java
  src/main/java/pickup_shuttle/pickup/domain/user/UserService.java
  src/main/java/pickup_shuttle/pickup/domain/user/dto/response/LoginUserRp.java
  src/main/java/pickup_shuttle/pickup/security/SecurityConfig.java
  src/main/java/pickup_shuttle/pickup/security/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/pickup_shuttle/pickup/security/service/JwtService.java
  src/main/resources/application-common.yml
  src/main/resources/application-dev-oauth.yml
  src/main/resources/application.yml
  src/main/resources/templates/index.html
  src/main/resources/templates/registerInput.html
  src/main/resources/templates/userModify.html
Labels: ✨feature
